[package]
name = "guff-ida"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guff = "0.1.7"
guff-matrix = "0.1.7"

